[tool.poetry]
name = "deep-learning-classification"
version = "0.1.0"
description = ""
authors = ["Patrikz <estagiario_patrikz@ciasc.sc.gov.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
